name: Publish
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  publish:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '8.x.x'
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@main
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@main
    - name: Pack
      run: dotnet pack Rampastring.Tools.csproj -p:AssemblyVersion=$env:GitVersion_AssemblySemVer -p:FileVersion=$env:GitVersion_AssemblySemFileVer -p:InformationalVersion=$env:GitVersion_InformationalVersion -p:PackageVersion=$env:GitVersion_NuGetVersionV2
    - name: Release
      run: gh release create v${{ env.GitVersion_SemVer) }} (Get-Item bin\Release\*.*nupkg) --generate-notes --target ${{ env.GitVersion_Sha }} ${{ env.GitVersion_PreReleaseTag != '' && '--prerelease' || '' }}
      env:
        GH_TOKEN: ${{ github.token }}